-- Supabase/PostgreSQL schema for ConsensusScope Streamlit deployments.
-- Run this in Supabase Dashboard -> SQL Editor before enabling external storage.
-- Use SUPABASE_SERVICE_ROLE_KEY in Streamlit Secrets. Do not commit real keys.

create table if not exists public.consensusscope_main_teacher_decisions (
  id bigint generated by default as identity primary key,
  reviewer_id text not null,
  feedback_item_id text not null,
  teacher_action text not null,
  risk_level text,
  issue_type text,
  review_priority text,
  item_payload jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(reviewer_id, feedback_item_id)
);

create index if not exists cs_main_teacher_decisions_reviewer_idx
  on public.consensusscope_main_teacher_decisions (reviewer_id, updated_at desc);

create table if not exists public.consensusscope_expert_sessions (
  session_id text primary key,
  expert_id text not null,
  batch_id text not null,
  annotation_mode text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  duration_seconds double precision not null default 0,
  unique(expert_id, batch_id, annotation_mode)
);

create table if not exists public.consensusscope_essay_annotations (
  id bigint generated by default as identity primary key,
  expert_id text not null,
  batch_id text not null,
  essay_id text not null,
  task_response_score integer,
  organization_score integer,
  coherence_score integer,
  grammar_accuracy_score integer,
  vocabulary_use_score integer,
  overall_writing_quality integer,
  main_problems text,
  teacher_review_priority text,
  teacher_comment text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  duration_seconds double precision not null default 0,
  unique(expert_id, batch_id, essay_id)
);

create table if not exists public.consensusscope_feedback_decisions (
  id bigint generated by default as identity primary key,
  expert_id text not null,
  batch_id text not null,
  feedback_item_id text not null,
  essay_id text not null,
  issue_type_teacher text,
  feedback_correctness text,
  teacher_acceptability text,
  teacher_safety_label text,
  meaning_preservation text,
  teacher_review_needed text,
  teacher_final_action text,
  teacher_corrected_feedback text,
  teacher_reason text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  duration_seconds double precision not null default 0,
  unique(expert_id, batch_id, feedback_item_id)
);

create table if not exists public.consensusscope_feedback_safety_checks (
  id bigint generated by default as identity primary key,
  expert_id text not null,
  batch_id text not null,
  feedback_item_id text not null,
  essay_id text not null,
  risk_reason_teacher text,
  rubric_dimension text,
  evidence_note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  duration_seconds double precision not null default 0,
  unique(expert_id, batch_id, feedback_item_id)
);

create table if not exists public.consensusscope_annotation_logs (
  id bigint generated by default as identity primary key,
  expert_id text not null,
  batch_id text not null,
  item_type text not null,
  item_id text not null,
  action text not null,
  details jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  duration_seconds double precision not null default 0
);

create index if not exists cs_expert_sessions_lookup_idx
  on public.consensusscope_expert_sessions (expert_id, batch_id, updated_at desc);

create index if not exists cs_essay_annotations_lookup_idx
  on public.consensusscope_essay_annotations (expert_id, batch_id, essay_id);

create index if not exists cs_feedback_decisions_lookup_idx
  on public.consensusscope_feedback_decisions (expert_id, batch_id, feedback_item_id);

create index if not exists cs_feedback_safety_lookup_idx
  on public.consensusscope_feedback_safety_checks (expert_id, batch_id, feedback_item_id);

create index if not exists cs_annotation_logs_lookup_idx
  on public.consensusscope_annotation_logs (expert_id, batch_id, created_at desc);

alter table public.consensusscope_main_teacher_decisions enable row level security;
alter table public.consensusscope_expert_sessions enable row level security;
alter table public.consensusscope_essay_annotations enable row level security;
alter table public.consensusscope_feedback_decisions enable row level security;
alter table public.consensusscope_feedback_safety_checks enable row level security;
alter table public.consensusscope_annotation_logs enable row level security;
